spring:
  config:
    import: aws-secretsmanager:prod/netflux/db/movie?prefix=db.
  datasource:
    url: jdbc:postgresql://${db.host}:5432/movie
    username: ${db.username}
    password: ${db.password}

server:
  port: 8080